# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=200)),
                ('url', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=200)),
                ('sale_price', models.CharField(default='', max_length=200)),
                ('currency', models.CharField(default='', max_length=200)),
                ('images', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifySettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proxy_api', models.CharField(blank=True, default='', max_length=100)),
                ('update_period', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifySiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(default='http://example.com', max_length=100)),
                ('total_products', models.IntegerField(default=0)),
                ('last_update_date', models.DateTimeField(default=datetime.datetime(2017, 12, 10, 16, 19, 42, 757107))),
                ('last_status', models.CharField(default='NONE', max_length=100)),
            ],
        ),
    ]
