# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysitemodel',
            name='last_status',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='shopifysitemodel',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 16, 50, 35, 74590)),
        ),
        migrations.AddField(
            model_name='shopifysitemodel',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='url',
            field=models.CharField(default='http://example.com', max_length=100),
        ),
    ]
