# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysettingsmodel',
            name='proxy_api',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 16, 26, 10, 462551)),
        ),
    ]
