# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171210_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 15, 59, 21, 370614)),
        ),
    ]
