# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171217_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifyproductmodel',
            name='website_id',
        ),
        migrations.AddField(
            model_name='shopifyproductmodel',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.ShopifySiteModel', verbose_name='Website that owns the product'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='category',
            field=models.CharField(default='', max_length=200, verbose_name='Product category name'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='currency',
            field=models.CharField(default='', max_length=200, verbose_name='Product currency'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Product short description'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='images',
            field=models.CharField(default='', max_length=2000, verbose_name='Product images urls, separated with ";"'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='price',
            field=models.CharField(default='', max_length=200, verbose_name='Product price'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='sale_price',
            field=models.CharField(default='', max_length=200, verbose_name='Product sale price'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Product title'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='Product url'),
        ),
        migrations.AlterField(
            model_name='shopifysettingsmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Settings name'),
        ),
        migrations.AlterField(
            model_name='shopifysettingsmodel',
            name='proxy_api',
            field=models.CharField(default='', max_length=100, verbose_name='Proxy api key'),
        ),
        migrations.AlterField(
            model_name='shopifysettingsmodel',
            name='update_period',
            field=models.IntegerField(default=60, verbose_name='Updating time period in seconds'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='last_status',
            field=models.CharField(default='NONE', max_length=100, verbose_name='Last update status'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 16, 20, 32, 182156), verbose_name='Last update date'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Website name'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='total_products',
            field=models.IntegerField(default=0, verbose_name='Total products amount'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='url',
            field=models.CharField(default='http://example.com', max_length=100, verbose_name='Website url'),
        ),
    ]
