# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171217_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='category',
            field=models.CharField(default='', max_length=200, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='currency',
            field=models.CharField(default='', max_length=200, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='images',
            field=models.CharField(default='', max_length=2000, verbose_name='Images urls'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='price',
            field=models.CharField(default='', max_length=200, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='sale_price',
            field=models.CharField(default='', max_length=200, verbose_name='Sale price'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='shopifyproductmodel',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.ShopifySiteModel', verbose_name='Parent website'),
        ),
        migrations.AlterField(
            model_name='shopifysettingsmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shopifysettingsmodel',
            name='update_period',
            field=models.IntegerField(default=60, verbose_name='Update after (sec)'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 16, 25, 17, 237678), verbose_name='Last update date'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='total_products',
            field=models.IntegerField(default=0, verbose_name='Total products'),
        ),
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='url',
            field=models.CharField(default='http://example.com', max_length=100, verbose_name='Url'),
        ),
    ]
