# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20171217_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysitemodel',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 16, 30, 24, 3220), verbose_name='Last update date'),
        ),
    ]
