Locations = {
    'Channel Islands': 'Channel_Islands/',
    'Suriname': 'suriname/',
    'Slovakia': 'slovakia/',
    'Jamaica': 'jamaica/',
    'Iceland': 'iceland/',
    'Cyprus': 'cyprus/',
    'Botswana': 'botswana/',
    'South-Africa': 'south-africa/',
    'Norway': 'norway/',
    'Bosnia and Herzegovina': 'bosnia_and_herzegovina/',
    'Montenegro': 'montenegro/',
    'Croatia': 'croatia/',
    'Canada': 'canada/',
    'Brazil': 'brazil/',
    'Peru': 'peru/',
    'Hungary': 'hungary/',
    'Greece': 'greece/',
    'Luxembourg': 'luxembourg/',
    'Costa rica': 'costa_rica/',
    'Belgium': 'belgium/',
    'Austria': 'austria/',
    'Switzerland': 'switzerland/',
    'Sweden': 'sweden/',
    'Argentina': 'argentina/',
    'Denmark': 'denmark/',
    'Chile': 'chile/',
    'Slovenia': 'slovenia/',
    'Australia': 'australia/',
    'Portugal': 'portugal/',
    'Germany': 'germany/',
    'Netherlands': 'netherlands/',
    'Italy': 'italy/',
    'Usa' : 'usa/',
    'Spain' : 'spain/',
    'France' : 'france/',
    'Scotland' : 'Scotland/',
    'NorthernIreland' : 'Northern_Ireland/',
    'RepublicOfIreland' : 'Republic-of-Ireland/',
    'Wales' : 'Wales/',
    'England' : 'England/',
    'EnglandSouthWest' : 'England/South_West/',
    'EnglandSouthEast' : 'England/South_East/',
    'EnglandEastAnglia' : 'England/East_Anglia/',
    'EnglandCentral' : 'England/Central/',
    'EnglandNorthWest' : 'England/North_West/',
    'EnglandNorthEast' : 'England/North_East/'
}